### ISSUE TITLE
Can't start audio recording

### ISSUE THREAD

**Issue by zinwalin** [ZaraclaJ/audio_recorder#22]
Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (3 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2

E/MethodChannel#audio_recorder(21439): Failed to handle method call
E/MethodChannel#audio_recorder(21439): java.lang.IllegalStateException
E/MethodChannel#audio_recorder(21439):  at android.media.MediaRecorder._start(Native Method)
E/MethodChannel#audio_recorder(21439):  at android.media.MediaRecorder.start(MediaRecorder.java:1175)
E/MethodChannel#audio_recorder(21439):  at com.jordanalcaraz.audiorecorder.audiorecorder.AudioRecorderPlugin.startRecording(AudioRecorderPlugin.java:107)
E/MethodChannel#audio_recorder(21439):  at com.jordanalcaraz.audiorecorder.audiorecorder.AudioRecorderPlugin.onMethodCall(AudioRecorderPlugin.java:59)
E/MethodChannel#audio_recorder(21439):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#audio_recorder(21439):  at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#audio_recorder(21439):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#audio_recorder(21439):  at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#audio_recorder(21439):  at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#audio_recorder(21439):  at android.app.ActivityThread.main(ActivityThread.java:6682)
E/MethodChannel#audio_recorder(21439):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#audio_recorder(21439):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/MethodChannel#audio_recorder(21439):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
I/flutter (21439): PlatformException(error, null, null)

**Comment by ZaraclaJ** [comment]
Can you send me a sample where i can reproduce your error ?

**Comment by somelikebit** [comment]
i have the same problem.
is it solved for you?
any solution ..

**Comment by AteqEjaz** [comment]
Hi Guys,

Same problem, it occurs when we click multiple time on 'Start' recording button.

Any suggestions?

Thanks
